### ISSUE TITLE
mock has been called

### ISSUE THREAD

**Issue by AdrienLemaire** [peoplenarthax/jest-mock-random#1]
Hi, and thanks for this package.

I would like to verify that the mock was called. How can I use `toHaveBeenCalled` or `toHaveBeenCalledTimes` on the mock created through mockRandom()?

**Comment by conatus** [comment]
You can work around this as follows using `jest.spyOn`.

```javascript
describe('mocked randomness', () => {
    afterAll(() => {
      resetMockRandom();
    })

    const useMathRandom = () => Math.random();

    it('should use Math.random()', () => {
      const mockedRandomNumber = 0.1
      mockRandom(mockedRandomNumber);

      const randomSpy = jest.spyOn(Math, 'random');

      expect(useMathRandom()).toEqual(mockedRandomNumber);
      expect(randomSpy).toBeCalledTimes(1);     
    });
});
```

**Comment by ZufengW** [comment]
> You can work around this as follows using `jest.spyOn`.

Seems like `jest.spyOn(Math, 'random')` is also a substitute for using this package.

For example:
```js
it('runs', () => {
  const randomSpy = jest.spyOn(Math, 'random');
  randomSpy.mockReturnValue(0);
  expect(foo()).toBe(1);
  randomSpy.mockReturnValue(0.99);
  expect(foo()).toBe(10);
  expect(randomSpy).toBeCalledTimes(2);
});
```
Or
```js
it('runs', () => {
  jest.spyOn(Math, 'random')
    .mockReturnValueOnce(0)
    .mockReturnValueOnce(0.99);
  expect(foo()).toBe(1);
  expect(foo()).toBe(10);
});
```

See: [jest.spyOn(object, methodName)](https://jestjs.io/docs/en/jest-object#jestspyonobject-methodname) and the [mock function API](https://jestjs.io/docs/en/mock-function-api)

**Comment by conatus** [comment]
Sure, that is how I’d have done it before encountering this package and for mocking any JavaScript internal. This package however has a nicer API and automatically tears the spy down for you and ensures you don’t mock it with something wacky like a string.

Seems to be a judgement call as to whether taking on another package is worthwhile, especially one where the API is unknown to the average reader, a bit “magic” and hence potentially makes tests less readable and maintainable.

**Comment by peoplenarthax** [comment]
> Hi, and thanks for this package.
> 
> I would like to verify that the mock was called. How can I use `toHaveBeenCalled` or `toHaveBeenCalledTimes` on the mock created through mockRandom()?

I am very late for this party, for some reason this never popped in my issues.

I did not thought of that while creating this package, but, as suggested by the workaround I think the best way to go was to use Spies on the original function (after all that is what you want to assert, that Math.random has been called, and then your testing library have a nice API for those things. 

The purpose of this package was to offer a more intuitive API for those who need deterministic results when using Math.random... of course it is just sugar-coating on top of your test framework. That is why I wanted to keep this package as small as possible.
